### ISSUE TITLE
Crash after selecting album

### ISSUE THREAD

**Issue by rubdos** [JakeStanger/Rofi_MPD#12]
And I'm back! :-)

```
Traceback (most recent call last):
  File "/usr/bin/rofi-mpd", line 303, in <module>
    select_album(selection_list, full_album=True)
  File "/usr/bin/rofi-mpd", line 258, in select_album
    select(artist or 'All Albums', data, full_album=full_album)
  File "/usr/bin/rofi-mpd", line 226, in select
    select_track(selection_list, selected_data['artist'], selected_data['album'])
  File "/usr/bin/rofi-mpd", line 267, in select_track
    key=lambda x: (int(x['data']['disc'] if 'disc' in x['data'] else 1),
  File "/usr/bin/rofi-mpd", line 267, in <lambda>
    key=lambda x: (int(x['data']['disc'] if 'disc' in x['data'] else 1),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```

Apparently this `disc` can be a list, but I have no clue what it means. Same with track number, apparently:

```
[{'type': <ItemType.track: 'track'>, 'data': {'file': 'TesseracT/One/01 Lament.opus', 'last-modified': '2018-07-22T19:49:07Z', 'time': '293', 'duration': '293.486', 'album': 'One', 'albumartist': 'TesseracT', 'albumartistsort': 'TesseracT', 'artist': 'TesseracT', 'artistsort': 'TesseracT', 'date': '2011-03-22', 'disc': ['1', '1'], 'genre': 'Progressive Metal', 'musicbrainz_albumartistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_albumid': 'a33554ec-30ac-45e2-835d-c93ed349c718', 'musicbrainz_artistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_trackid': 'a4229593-32d1-4c6d-a97c-88486712f761', 'title': 'Lament', 'track': ['1', '1']}}, {'type': <ItemType.track: 'track'>, 'data': {'file': 'TesseracT/One/02 Nascent.opus', 'last-modified': '2018-07-22T19:49:07Z', 'time': '249', 'duration': '249.313', 'album': 'One', 'albumartist': 'TesseracT', 'albumartistsort': 'TesseracT', 'artist': 'TesseracT', 'artistsort': 'TesseracT', 'date': '2011-03-22', 'disc': ['1', '1'], 'genre': 'Progressive Metal', 'musicbrainz_albumartistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_albumid': 'a33554ec-30ac-45e2-835d-c93ed349c718', 'musicbrainz_artistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_trackid': 'd9966081-a00d-4103-8fec-e8ce0831ccd5', 'title': 'Nascent', 'track': ['2', '2']}}, {'type': <ItemType.track: 'track'>, 'data': {'file': 'TesseracT/One/03 Concealing Fate, Part 1_ Acceptance.opus', 'last-modified': '2018-07-22T19:49:07Z', 'time': '514', 'duration': '513.566', 'album': 'One', 'albumartist': 'TesseracT', 'albumartistsort': 'TesseracT', 'artist': 'TesseracT', 'artistsort': 'TesseracT', 'date': '2011-03-22', 'disc': ['1', '1'], 'genre': 'Progressive Metal', 'musicbrainz_albumartistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_albumid': 'a33554ec-30ac-45e2-835d-c93ed349c718', 'musicbrainz_artistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_trackid': '885db8e6-aedd-43cf-8af3-6aee3e39e300', 'title': 'Concealing Fate, Part 1: Acceptance', 'track': ['3', '3']}}, {'type': <ItemType.track: 'track'>, 'data': {'file': 'TesseracT/One/04 Concealing Fate, Part 2_ Deception.opus', 'last-modified': '2018-07-22T19:49:07Z', 'time': '323', 'duration': '322.873', 'album': 'One', 'albumartist': 'TesseracT', 'albumartistsort': 'TesseracT', 'artist': 'TesseracT', 'artistsort': 'TesseracT', 'date': '2011-03-22', 'disc': ['1', '1'], 'genre': 'Progressive Metal', 'musicbrainz_albumartistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_albumid': 'a33554ec-30ac-45e2-835d-c93ed349c718', 'musicbrainz_artistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_trackid': '042ce449-79ee-4106-a03e-9ea5256a4391', 'title': 'Concealing Fate, Part 2: Deception', 'track': ['4', '4']}}, {'type': <ItemType.track: 'track'>, 'data': {'file': 'TesseracT/One/05 Concealing Fate, Part 3_ The Impossible.opus', 'last-modified': '2018-07-22T19:49:07Z', 'time': '291', 'duration': '290.806', 'album': 'One', 'albumartist': 'TesseracT', 'albumartistsort': 'TesseracT', 'artist': 'TesseracT', 'artistsort': 'TesseracT', 'date': '2011-03-22', 'disc': ['1', '1'], 'genre': 'Progressive Metal', 'musicbrainz_albumartistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_albumid': 'a33554ec-30ac-45e2-835d-c93ed349c718', 'musicbrainz_artistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_trackid': 'a598391c-bd49-48bf-b7e4-fe28fb26720f', 'title': 'Concealing Fate, Part 3: The Impossible', 'track': ['5', '5']}}, {'type': <ItemType.track: 'track'>, 'data': {'file': 'TesseracT/One/06 Concealing Fate, Part 4_ Perfection.opus', 'last-modified': '2018-07-22T19:49:07Z', 'time': '158', 'duration': '158.286', 'album': 'One', 'albumartist': 'TesseracT', 'albumartistsort': 'TesseracT', 'artist': 'TesseracT', 'artistsort': 'TesseracT', 'date': '2011-03-22', 'disc': ['1', '1'], 'genre': 'Progressive Metal', 'musicbrainz_albumartistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_albumid': 'a33554ec-30ac-45e2-835d-c93ed349c718', 'musicbrainz_artistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_trackid': 'a031b366-7500-4ea5-be98-a6f6a49de6ff', 'title': 'Concealing Fate, Part 4: Perfection', 'track': ['6', '6']}}, {'type': <ItemType.track: 'track'>, 'data': {'file': 'TesseracT/One/07 Concealing Fate, Part 5_ Epiphany.opus', 'last-modified': '2018-07-22T19:49:07Z', 'time': '89', 'duration': '89.246', 'album': 'One', 'albumartist': 'TesseracT', 'albumartistsort': 'TesseracT', 'artist': 'TesseracT', 'artistsort': 'TesseracT', 'date': '2011-03-22', 'disc': ['1', '1'], 'genre': 'Progressive Metal', 'musicbrainz_albumartistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_albumid': 'a33554ec-30ac-45e2-835d-c93ed349c718', 'musicbrainz_artistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_trackid': '9fd1f32c-7819-4a0f-90ee-1330445c7fcf', 'title': 'Concealing Fate, Part 5: Epiphany', 'track': ['7', '7']}}, {'type': <ItemType.track: 'track'>, 'data': {'file': 'TesseracT/One/08 Concealing Fate, Part 6_ Origin.opus', 'last-modified': '2018-07-22T19:49:07Z', 'time': '284', 'duration': '284.446', 'album': 'One', 'albumartist': 'TesseracT', 'albumartistsort': 'TesseracT', 'artist': 'TesseracT', 'artistsort': 'TesseracT', 'date': '2011-03-22', 'disc': ['1', '1'], 'genre': 'Progressive Metal', 'musicbrainz_albumartistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_albumid': 'a33554ec-30ac-45e2-835d-c93ed349c718', 'musicbrainz_artistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_trackid': '4eb3f3d3-dad4-4b4d-8893-1d7a79577627', 'title': 'Concealing Fate, Part 6: Origin', 'track': ['8', '8']}}, {'type': <ItemType.track: 'track'>, 'data': {'file': 'TesseracT/One/09 Sunrise.opus', 'last-modified': '2018-07-22T19:49:07Z', 'time': '237', 'duration': '237.353', 'album': 'One', 'albumartist': 'TesseracT', 'albumartistsort': 'TesseracT', 'artist': 'TesseracT', 'artistsort': 'TesseracT', 'date': '2011-03-22', 'disc': ['1', '1'], 'genre': 'Progressive Metal', 'musicbrainz_albumartistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_albumid': 'a33554ec-30ac-45e2-835d-c93ed349c718', 'musicbrainz_artistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_trackid': '5df4b626-18ea-4dff-8959-a3fed358fb2a', 'title': 'Sunrise', 'track': ['9', '9']}}, {'type': <ItemType.track: 'track'>, 'data': {'file': 'TesseracT/One/10 April.opus', 'last-modified': '2018-07-22T19:49:07Z', 'time': '289', 'duration': '288.939', 'album': 'One', 'albumartist': 'TesseracT', 'albumartistsort': 'TesseracT', 'artist': 'TesseracT', 'artistsort': 'TesseracT', 'date': '2011-03-22', 'disc': ['1', '1'], 'genre': 'Progressive Metal', 'musicbrainz_albumartistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_albumid': 'a33554ec-30ac-45e2-835d-c93ed349c718', 'musicbrainz_artistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_trackid': '22a976f1-77f1-45a5-8d2b-2f6238dbb417', 'title': 'April', 'track': ['10', '10']}}, {'type': <ItemType.track: 'track'>, 'data': {'file': 'TesseracT/One/11 Eden.opus', 'last-modified': '2018-07-22T19:49:07Z', 'time': '548', 'duration': '548.206', 'album': 'One', 'albumartist': 'TesseracT', 'albumartistsort': 'TesseracT', 'artist': 'TesseracT', 'artistsort': 'TesseracT', 'date': '2011-03-22', 'disc': ['1', '1'], 'genre': 'Progressive Metal', 'musicbrainz_albumartistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_albumid': 'a33554ec-30ac-45e2-835d-c93ed349c718', 'musicbrainz_artistid': 'f1ec4765-e5da-4591-8b50-a8ff9627dda8', 'musicbrainz_trackid': 'ce64b533-8f2f-41c9-b2d3-990e273cf3a4', 'title': 'Eden', 'track': ['11', '11']}}]
```

This is a dump of `list(data)` just before the crash site mentioned above.

Both `track` and `disc` apparently give a list of twice their number...: `'disc': ['1', '1'], 'track': ['11', '11']`

**Comment by JakeStanger** [comment]
It sounds like you've got some weirdly tagged tracks. I think mpd supports all tags being a list, so I'll put in a proper fix for that tonight after work.

**Comment by JakeStanger** [comment]
Does 5aed090 fix it for you? Any lists are replaced with their first value when the database is generated now.

**Comment by rubdos** [comment]
Looks correct now!

**Comment by rubdos** [comment]
FYI: I have rofi-mpd binded to a key in `sway`, and it works now :-)
