### ISSUE TITLE
KeyError when album is not specified

### ISSUE THREAD

**Issue by EgZvor** [JakeStanger/Rofi_MPD#8]
```
Traceback (most recent call last):
  File "main.py", line 270, in <module>
    select_artist(selection_list)
  File "main.py", line 217, in select_artist
    select(title or 'All Artists', [*data])
  File "main.py", line 188, in select
    select_album(selection_list, selected_data)
  File "main.py", line 223, in select_album
    select(artist or 'All Albums', data, full_album=full_album)
  File "main.py", line 191, in select
    select_track(selection_list, selected_data['artist'], selected_data['album'])
  File "main.py", line 231, in select_track
    data = sorted([*data],
  File "main.py", line 229, in <lambda>
    and (x['data']['album'] == album if album else True), data)
KeyError: 'album'
```

**Comment by JakeStanger** [comment]
Hi, could you give me the data causing this to fail please? I'm struggling to see why this would happen from just the code/error.

**Comment by EgZvor** [comment]
```
➜ ~/Music id3 Wallace\ Collection\ -\ Daydream.mp3 
File: Wallace Collection - Daydream.mp3
Metadata: ID3v2.3
Title: Daydream
Artist: Wallace Collection
```

**Comment by EgZvor** [comment]
You can delete tags with `id3 --delete <filename>`

**Comment by EgZvor** [comment]
I think it's because of this.
```
            # Handle songs with missing album tag
            if 'album' in song:
                album = song['album']
            else:
                album = "[Unknown Album]"
```
`[Unknown Album]` is then used as a value, an the check `if album` doesn't apply.

**Comment by JakeStanger** [comment]
Yep, it was exactly that! It should be fixed now.
